spring:
  application:
    name: api-gateway
    cloud:
      gateway:
        routes:
          - id: aluno
            uri: lb://api-pessoa
            predicates:
              - Path=/aluno/**
          - id: professor
            uri: lb://api-pessoa
            predicates:
              - Path=/professor/**
          - id: login
            uri: lb://api-pessoa
            predicates:
              - Path=/loginr/**
          - id: auth
            uri: lb://auth
            predicates:
             - Path=/auth/**

server:
  port: 8080

  management:
    endpoints:
      web:
        exposure:
          include: '*'
  zuul:
    ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
    routes:
      auth:
        path: /auth/**
        sensitive-headers: Cookie,Set-Cookie
        service-id: auth
      api-pessoa:
        path: /login/**
        service-id: api-pessoa

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
