server:
  port: 8080
spring:
  application:
    name: gateway

management:
  endpoints:
    web:
      exposure:
        include: '*'
zuul:
  ignored-headers: Access-Control-Allow-Credentials, Access-Control-Allow-Origin
  routes:
    auth:
      path: /auth/**
      sensitive-headers: Cookie,Set-Cookie
      service-id: auth

      springdoc:
        api-docs:
          path: usuario
        swagger-ui:
          path: /swagger-ui/#/index.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

      hystrix:
        command:
          default:
            execution:
              isolation:
                thread:
                  timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 20000

